version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: volunteer_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Wnn0705520@
      MYSQL_DATABASE: volunteer_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: